//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kampanya
    {
        public int kampanyaID { get; set; }
        public int urunID { get; set; }
        public int kampanyaYuzdesi { get; set; }
        public bool aktif { get; set; }
    
        public virtual urunler urunler { get; set; }
    }
}
