//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restoranGetir
    {
        public int restoranID { get; set; }
        public string restoranAdi { get; set; }
        public int sirketID { get; set; }
        public int ilID { get; set; }
        public int ilceID { get; set; }
        public bool silindi { get; set; }
        public string ilAdi { get; set; }
        public string ilceAdi { get; set; }
        public string sirketAdi { get; set; }
    }
}
