//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int siparisID { get; set; }
        public int musteriID { get; set; }
        public System.DateTime tarih { get; set; }
        public int urunId { get; set; }
        public bool tamamlandi { get; set; }
    
        public virtual musteri musteri { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
