//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisGetir
    {
        public string ad { get; set; }
        public string soyad { get; set; }
        public int siparisID { get; set; }
        public int musteriID { get; set; }
        public System.DateTime tarih { get; set; }
        public bool tamamlandi { get; set; }
        public int urunID { get; set; }
        public int restoranID { get; set; }
        public string urunAdi { get; set; }
        public double fiyat { get; set; }
        public int kategoriID { get; set; }
        public bool silindi { get; set; }
    }
}
