//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunGetir2
    {
        public Nullable<int> kampanyaYuzdesi { get; set; }
        public Nullable<int> kampanyaID { get; set; }
        public int urunID { get; set; }
        public int restoranID { get; set; }
        public string urunAdi { get; set; }
        public double fiyat { get; set; }
        public int kategoriID { get; set; }
        public bool silindi { get; set; }
        public string kategoriAdi { get; set; }
    }
}
