//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekProjeEntities1 : DbContext
    {
        public YemekProjeEntities1()
            : base("name=YemekProjeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminler> adminler { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<kampanya> kampanya { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<restoran> restoran { get; set; }
        public virtual DbSet<siparisler> siparisler { get; set; }
        public virtual DbSet<sirket> sirket { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<restoranGetir> restoranGetir { get; set; }
        public virtual DbSet<urunGetir> urunGetir { get; set; }
        public virtual DbSet<urunGetir2> urunGetir2 { get; set; }
        public virtual DbSet<siparisGetir> siparisGetir { get; set; }
    }
}
